-- New databases only. Existing databases require schema comparison and explicit baseline 1.
-- Do not add IF NOT EXISTS to tables: an unexpected existing schema must fail closed.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE families (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invite_code varchar(6) NOT NULL UNIQUE,
    created_at timestamp(6)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255),
    provider varchar(255) NOT NULL,
    email_verified boolean NOT NULL,
    name varchar(255) NOT NULL,
    nickname varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    birth_date date,
    phone_number varchar(255),
    address varchar(255),
    verification_code varchar(255),
    code_created_at timestamp(6),
    family_id bigint REFERENCES families(id)
);

CREATE TABLE babies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    gender varchar(1) NOT NULL,
    birth_date date NOT NULL,
    weight double precision,
    height double precision,
    special_notes varchar(500),
    created_at timestamp(6),
    family_id bigint NOT NULL REFERENCES families(id)
);

CREATE TABLE admins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(6),
    last_login_at timestamp(6)
);

CREATE TABLE boards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(200),
    display_order integer,
    board_type varchar(255) NOT NULL,
    active boolean NOT NULL
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    icon varchar(255),
    display_order integer
);

CREATE TABLE chatbot_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key varchar(255) NOT NULL UNIQUE,
    config_value text NOT NULL,
    description varchar(300),
    updated_at timestamp(6)
);

CREATE TABLE chat_room (
    id varchar(255) PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    title varchar(255),
    is_active boolean NOT NULL,
    created_at timestamp(6)
);

CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id varchar(255) NOT NULL REFERENCES chat_room(id),
    role varchar(255) NOT NULL CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    content text NOT NULL,
    token_count integer NOT NULL,
    created_at timestamp(6)
);

CREATE TABLE daily_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_time timestamp(6) NOT NULL,
    formula_amount integer,
    breastfed boolean,
    diaper_type varchar(255),
    memo varchar(500),
    baby_id bigint NOT NULL REFERENCES babies(id),
    user_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp(6)
);

CREATE TABLE records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type varchar(255) NOT NULL,
    amount integer,
    memo varchar(255),
    record_time timestamp(6),
    baby_id bigint REFERENCES babies(id),
    user_id bigint REFERENCES users(id)
);

CREATE TABLE community_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    image_urls text,
    board_id bigint NOT NULL REFERENCES boards(id),
    user_id bigint NOT NULL REFERENCES users(id),
    view_count integer NOT NULL,
    comment_count integer NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6)
);

CREATE TABLE community_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content varchar(1000) NOT NULL,
    post_id bigint NOT NULL REFERENCES community_posts(id),
    user_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp(6)
);

CREATE TABLE notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    pinned boolean NOT NULL,
    active boolean NOT NULL,
    author_id bigint REFERENCES admins(id),
    created_at timestamp(6),
    updated_at timestamp(6)
);

-- This parameter creates the first table; it never resizes existing embeddings.
-- No approximate vector index is created: 3072-dimensional vectors exceed HNSW's
-- vector limit. Index changes belong in a separately reviewed versioned migration.
CREATE TABLE vector_store (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    content text,
    metadata json,
    embedding vector(${vectorDimensions})
);
